# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 48) do

  create_table "agencies", :force => true do |t|
    t.column "fio", :string, :limit => 200, :default => ""
    t.column "name", :string, :limit => 200, :default => ""
    t.column "address", :string, :limit => 200, :default => ""
    t.column "phone1", :string, :limit => 100, :default => ""
    t.column "phone2", :string, :limit => 100, :default => ""
    t.column "email", :string, :limit => 200
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "buildings", :force => true do |t|
    t.column "building", :string, :limit => 200, :default => "", :null => false
  end

  create_table "buildings_lots", :id => false, :force => true do |t|
    t.column "lot_id", :integer, :default => 0, :null => false
    t.column "building_id", :integer, :default => 0, :null => false
  end

  add_index "buildings_lots", ["lot_id", "building_id"], :name => "ind"

  create_table "buildobjects", :force => true do |t|
    t.column "name", :string, :limit => 200, :default => "", :null => false
  end

  create_table "buildobjects_lots", :id => false, :force => true do |t|
    t.column "lot_id", :integer, :default => 0, :null => false
    t.column "buildobject_id", :integer, :default => 0, :null => false
  end

  add_index "buildobjects_lots", ["lot_id", "buildobject_id"], :name => "composite"

  create_table "city_distances", :force => true do |t|
    t.column "distance", :string, :limit => 200, :default => "", :null => false
    t.column "min_distance", :integer, :default => 0, :null => false
    t.column "max_distance", :integer, :default => 0, :null => false
  end

  create_table "contact_requests", :force => true do |t|
    t.column "name", :string
    t.column "phone", :string
    t.column "email", :string
    t.column "lot_id", :integer, :default => 0, :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "departures", :force => true do |t|
    t.column "departure", :string, :limit => 200, :default => "", :null => false
    t.column "xpoint", :integer, :default => 0, :null => false
    t.column "ypoint", :integer, :default => 0, :null => false
    t.column "image", :string, :limit => 150, :default => "", :null => false
    t.column "image2", :string, :limit => 150, :default => "", :null => false
    t.column "title", :string, :limit => 150, :default => "", :null => false
    t.column "name", :string, :limit => 150, :default => "", :null => false
  end

  create_table "electricities", :force => true do |t|
    t.column "distance", :string, :limit => 200, :default => "", :null => false
  end

  create_table "full_prices", :force => true do |t|
    t.column "price", :string, :limit => 200, :default => "", :null => false
    t.column "min_price", :float, :default => 0.0, :null => false
    t.column "max_price", :float, :default => 0.0, :null => false
  end

  create_table "gas", :force => true do |t|
    t.column "distance", :string, :limit => 200, :default => "", :null => false
  end

  create_table "greens", :force => true do |t|
    t.column "green", :string, :limit => 200, :default => "", :null => false
  end

  create_table "greens_lots", :id => false, :force => true do |t|
    t.column "lot_id", :integer, :default => 0, :null => false
    t.column "green_id", :integer, :default => 0, :null => false
  end

  add_index "greens_lots", ["lot_id", "green_id"], :name => "lot_green"

  create_table "grounds", :force => true do |t|
    t.column "ground", :string, :limit => 200, :default => "", :null => false
  end

  create_table "groundwater_levels", :force => true do |t|
    t.column "level", :string, :limit => 200, :default => "", :null => false
  end

  create_table "lotroad_distances", :force => true do |t|
    t.column "distance", :string, :limit => 150, :default => "", :null => false
  end

  create_table "lotroad_surfaces", :force => true do |t|
    t.column "surface", :string, :limit => 200, :default => "", :null => false
  end

  create_table "lotroad_widths", :force => true do |t|
    t.column "width", :string, :limit => 200, :default => "", :null => false
  end

  create_table "lots", :force => true do |t|
    t.column "area", :string, :limit => 200, :default => "", :null => false
    t.column "square", :float, :default => 0.0, :null => false
    t.column "price_per_square", :integer, :default => 0, :null => false
    t.column "is_price_changeble", :boolean, :default => false, :null => false
    t.column "distance_to_city", :float, :default => 0.0, :null => false
    t.column "departure_id", :integer, :default => 0, :null => false
    t.column "lotroad_distance_id", :integer, :default => 0, :null => false
    t.column "lotroad_surface_id", :integer, :default => 0, :null => false
    t.column "lotroad_width_id", :integer, :default => 0, :null => false
    t.column "is_another_routes", :boolean, :default => false, :null => false
    t.column "gas_id", :integer, :default => 0, :null => false
    t.column "electricity_id", :integer, :default => 0, :null => false
    t.column "water_id", :integer, :default => 0, :null => false
    t.column "nearest_shop_distance", :float, :default => 0.0
    t.column "nearest_kiosk_distance", :float, :default => 0.0
    t.column "nearest_commerce_another", :text
    t.column "placement_id", :integer, :default => 0, :null => false
    t.column "placement_another", :text, :default => "", :null => false
    t.column "nature_types_another", :text, :default => "", :null => false
    t.column "lot_length", :float, :default => 0.0, :null => false
    t.column "lot_width", :float, :default => 0.0, :null => false
    t.column "lot_shape", :string, :limit => 200, :default => "", :null => false
    t.column "ground_id", :integer, :default => 0, :null => false
    t.column "ground_another", :text, :default => "", :null => false
    t.column "building_another", :text, :default => "", :null => false
    t.column "green_another", :string, :limit => 200, :default => "", :null => false
    t.column "relief_another", :text, :default => "", :null => false
    t.column "groundwater_level_id", :integer, :default => 0, :null => false
    t.column "noise_source_another", :text, :default => "", :null => false
    t.column "buildobjects_another", :text, :default => "", :null => false
    t.column "extra_info", :text, :default => "", :null => false
    t.column "region_id", :integer, :default => 0, :null => false
    t.column "square_for_building", :float, :default => 0.0, :null => false
    t.column "noise_id", :integer, :default => 0, :null => false
    t.column "full_price", :integer, :default => 0, :null => false
    t.column "lotroad_surface_another", :string, :limit => 200, :default => "", :null => false
    t.column "nearest_shop_distance_another", :string, :limit => 200, :default => "", :null => false
    t.column "is_reviewed", :boolean, :default => false, :null => false
    t.column "point_x", :integer, :default => 0, :null => false
    t.column "point_y", :integer, :default => 0, :null => false
    t.column "agency_id", :integer
    t.column "owner_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "feature1", :string
    t.column "feature2", :string
    t.column "feature1name", :string
    t.column "feature2name", :string
    t.column "weights", :integer, :default => 0
    t.column "selected_photo_id", :integer
  end

  add_index "lots", ["area"], :name => "areaindex"
  add_index "lots", ["square"], :name => "squareindex"
  add_index "lots", ["departure_id"], :name => "departure_id"
  add_index "lots", ["lotroad_distance_id"], :name => "distance_to_road"
  add_index "lots", ["lotroad_surface_id"], :name => "surface_to_road"
  add_index "lots", ["lotroad_width_id"], :name => "surface_width"
  add_index "lots", ["gas_id"], :name => "gas"
  add_index "lots", ["electricity_id"], :name => "electricity"
  add_index "lots", ["water_id"], :name => "water"
  add_index "lots", ["placement_id"], :name => "placement"
  add_index "lots", ["ground_id"], :name => "ground"
  add_index "lots", ["groundwater_level_id"], :name => "groundwater"
  add_index "lots", ["region_id"], :name => "region_id"
  add_index "lots", ["noise_id"], :name => "noise_id"
  add_index "lots", ["full_price"], :name => "full_price"
  add_index "lots", ["owner_id"], :name => "owner_id"
  add_index "lots", ["agency_id"], :name => "agency_id"

  create_table "lots_natures", :force => true do |t|
    t.column "lot_id", :integer, :default => 0
    t.column "nature_type_id", :integer, :default => 0
    t.column "nature_distance_id", :integer, :default => 0
  end

  add_index "lots_natures", ["nature_type_id", "nature_distance_id"], :name => "lots_natures_index"

  create_table "lots_neighbours", :force => true do |t|
    t.column "lot_id", :integer, :default => 0
    t.column "neighbour_distance_id", :integer, :default => 0
    t.column "neighbour_type_id", :integer, :default => 0
  end

  add_index "lots_neighbours", ["neighbour_distance_id", "neighbour_type_id"], :name => "lots_neighbours_index"

  create_table "lots_noise_sources", :id => false, :force => true do |t|
    t.column "lot_id", :integer, :default => 0, :null => false
    t.column "noise_source_id", :integer, :default => 0, :null => false
  end

  add_index "lots_noise_sources", ["lot_id", "noise_source_id"], :name => "lots_noise_sources_index"

  create_table "lots_reliefs", :id => false, :force => true do |t|
    t.column "lot_id", :integer, :default => 0, :null => false
    t.column "relief_id", :integer, :default => 0, :null => false
  end

  add_index "lots_reliefs", ["lot_id", "relief_id"], :name => "lots_reliefs_index"

  create_table "lots_routes", :force => true do |t|
    t.column "lot_id", :integer, :default => 0
    t.column "route_distance_id", :integer, :default => 0
    t.column "route_type_id", :integer, :default => 0
  end

  add_index "lots_routes", ["route_distance_id", "route_type_id"], :name => "lots_routes_index"

  create_table "nature_distances", :force => true do |t|
    t.column "distance", :string, :limit => 200, :default => "", :null => false
  end

  create_table "nature_types", :force => true do |t|
    t.column "nature", :string, :limit => 200, :default => "", :null => false
    t.column "has_distance", :integer, :default => 1, :null => false
  end

  add_index "nature_types", ["has_distance"], :name => "has_distance"

  create_table "neighbour_distances", :force => true do |t|
    t.column "distance", :string, :limit => 200, :default => "", :null => false
  end

  create_table "neighbour_types", :force => true do |t|
    t.column "neighbour", :string, :limit => 200, :default => "", :null => false
    t.column "has_distance", :integer, :default => 1, :null => false
  end

  create_table "noise_sources", :force => true do |t|
    t.column "source", :string, :limit => 150, :default => "", :null => false
  end

  create_table "noises", :force => true do |t|
    t.column "noise", :string, :limit => 150, :default => "", :null => false
  end

  create_table "owners", :force => true do |t|
    t.column "fio", :string, :limit => 200, :default => ""
    t.column "phone_city", :string, :limit => 200, :default => ""
    t.column "phone", :string, :limit => 200, :default => ""
    t.column "another_contact_fio", :string, :limit => 200
    t.column "another_contact_phone", :string, :limit => 200
    t.column "email", :string, :limit => 200
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "is_other_contacts_allowed", :integer, :default => 0, :null => false
    t.column "preferred_contact_type", :string, :limit => 100
  end

  create_table "pages", :force => true do |t|
    t.column "parent_id", :integer, :default => 0
    t.column "url", :string
    t.column "text", :text
    t.column "is_published", :integer, :limit => 4
    t.column "in_top_menu", :string, :limit => 0, :default => ""
    t.column "has_left_menu", :integer, :default => 0
    t.column "title", :string
    t.column "preview", :text
    t.column "keywords", :text, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
  end

  add_index "pages", ["parent_id"], :name => "page_parent_id"

  create_table "photos", :force => true do |t|
    t.column "lot_id", :integer, :default => 0, :null => false
    t.column "image", :string, :limit => 200, :default => "", :null => false
    t.column "weight", :integer, :default => 0
  end

  add_index "photos", ["lot_id"], :name => "lotid"

  create_table "placements", :force => true do |t|
    t.column "placement", :string, :limit => 200, :default => "", :null => false
  end

  create_table "prices", :force => true do |t|
    t.column "price", :string, :limit => 100, :default => "0", :null => false
    t.column "min_price", :float, :default => 0.0, :null => false
    t.column "max_price", :float, :default => 0.0, :null => false
  end

  create_table "regions", :force => true do |t|
    t.column "name", :string, :limit => 200, :default => "", :null => false
  end

  create_table "reliefs", :force => true do |t|
    t.column "relief", :string, :limit => 200, :default => "", :null => false
  end

  create_table "route_distances", :force => true do |t|
    t.column "distance", :string, :limit => 150, :default => "", :null => false
  end

  create_table "route_types", :force => true do |t|
    t.column "route", :string, :limit => 200, :default => "", :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "squares", :force => true do |t|
    t.column "square", :string, :limit => 100, :default => "", :null => false
    t.column "min_square", :float, :default => 0.0, :null => false
    t.column "max_square", :float, :default => 0.0, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80
    t.column "password", :string, :limit => 40
  end

  create_table "waters", :force => true do |t|
    t.column "object", :string, :limit => 200, :default => "", :null => false
  end

end
